development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: timesheets
  pool: 5
  username: neopoly
  password: neopoly
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: timesheets_test
  pool: 5
  username: neopoly
  password: neopoly
  socket: /var/run/mysqld/mysqld.sock

production: development 